---
title: "BlogCode"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(janitor)
library(tidyverse)
library(lubridate)
library(ical)
library(mosaic)
library(kableExtra)
library(lme4)
```



```{r}
# read in WorldData for Leaflet plot
WorldData <- read_csv('worldData.csv')

# read in ungrouped esg data for US map 
esg <- read_csv('ESG_data2.csv')

# read in wrangled Sector-Grouped data for visuals and stat analyses 
esg_grouped <- read_csv('ESG_grouped.csv')

# esg risk rating by Sector Group; Boxplot 
box <- ggplot(data = esg_grouped, aes(y = sector_group, x = esg)) +
  geom_boxplot(aes(color = sector_group)) +
  ggtitle('ESG Score by Sector Group') +
  labs(x = 'ESG Score', y = 'Sector Group') +
  theme_light()

box + theme(legend.position = "none")

# briefly wrangle for table output -- summarize function to grab mean and medians
esg_table <- esg_grouped %>%
  group_by(sector_group) %>%
  summarize('mean_score' = mean(esg), 'median_score' = median(esg), 
            'std_deviation' = sd(esg)) %>%
  arrange(desc(median_score))

# table output: mean/median/sd of esg risk for each sector group
kable(esg_table, digits = 4, format = "html", row.names = FALSE,
      col.names = c('Sector Group', 'Mean Score', 'Median Score',
                               'Std. Deviation'), 
      caption = 'ESG Score by Sector Group') %>%
  kable_styling(bootstrap_options = c("striped", "hover"),
                full_width = F,
                font_size = 14,
                position = "left")


# Check assumptions for linear regression. Will check for each sector group, and for
# aggregate case / all observations together 

# esg and revenue growth, point 
gpoint <- ggplot(data = esg_grouped, aes(x = esg, y = revenue_growth)) +
  geom_point(aes(color = sector_group)) +
  stat_smooth(aes(group = sector_group, color = sector_group), method = "lm", se = FALSE) +
  ggtitle('ESG Score and Revenue Growth') +
  labs(x = 'ESG Score', y = 'Revenue Growth (%)', color = 'Sector Group') +
  theme_light()

gpoint

# check linearity across all sector groups

# no transformation
gpoint_check <- ggplot(data = esg_grouped, aes(x = esg, y = revenue_growth)) +
  geom_point() + facet_wrap(~ sector_group)

gpoint_check

# log transformation
gpoint_check2 <- ggplot(data = esg_grouped, aes(x = log(esg), y = log(revenue_growth))) +
  geom_point() + facet_wrap(~ sector_group)

gpoint_check2

# square root transformation
gpoint_check3 <- ggplot(data = esg_grouped, aes(x = sqrt(esg), y = sqrt(revenue_growth))) +
  geom_point() + facet_wrap(~ sector_group)

gpoint_check3

# check normality across all sector groups for esg scores

# no transformation
ghist_check <- ggplot(data = esg_grouped, aes(x = esg)) +
  geom_histogram() + facet_wrap(~ sector_group)

ghist_check

# log transformation
ghist_check2 <- ggplot(data = esg_grouped, aes(x = log(esg))) +
  geom_histogram() + facet_wrap(~ sector_group)

ghist_check2

# square root transformation
ghist_check3 <- ggplot(data = esg_grouped, aes(x = sqrt(esg))) +
  geom_histogram() + facet_wrap(~ sector_group)

ghist_check3

# check normality across all sector groups for revenue growth 

# regular
ghist_check_rev <- ggplot(data = esg_grouped, aes(x = revenue_growth)) +
  geom_histogram() + facet_wrap(~ sector_group)

ghist_check_rev

# log transformation
ghist_check_rev2 <- ggplot(data = esg_grouped, aes(x = log(revenue_growth))) +
  geom_histogram() + facet_wrap(~ sector_group)

ghist_check_rev2

# sqrt transformation
ghist_check_rev3 <- ggplot(data = esg_grouped, aes(x = sqrt(revenue_growth))) +
  geom_histogram() + facet_wrap(~ sector_group)

ghist_check_rev3

# checking linearity for aggregate case
# no transformation
gf_point(revenue_growth ~ esg, data = esg_grouped)
# log transformation
gf_point(log(revenue_growth) ~ esg, data = esg_grouped)
# sqrt transformation
gf_point(sqrt(revenue_growth) ~ sqrt(esg), data = esg_grouped)

# checking normality assumption
# regular / untransformed revenue growth is skewed to the right 
gf_histogram(~revenue_growth, data = esg_grouped)
# log transformation on revenue growth 
gf_histogram(~log(revenue_growth), data = esg_grouped)

# checking assumptions: conclusion 
# it appears that both log and sqrt transformations have a marginal effect
# on linearity and normality for each sector group. When these transformations
# are applied, some of the sector groups become more linear / normal, while
# others stay the 'same' or arguably become less linear / normal. In the aggregate
# case, log and sqrt transformations also don't seem to have an impact on linearity, 
# though the log transformation does increase normality for revenue growth. But, 
# based on the transformations for each sector group, we decide to move forward with
# the regular, untransformed data. We recognize that the assumptions for linear 
# regression are not strongly met and understand the potential limitations of our results. 


# point plot, with regression lines, for Revenue Growth and ESG Rating

gpoint <- ggplot(data = esg_grouped, aes(x = esg, y = revenue_growth)) +
  geom_point(aes(color = sector_group)) +
  stat_smooth(aes(group = sector_group, color = sector_group), method = "lm", se = FALSE) +
  ggtitle('ESG Score and Revenue Growth') +
  labs(x = 'ESG Score', y = 'Revenue Growth (%)', color = 'Sector Group') +
  theme_light()

gpoint



# overall linear regression between revenue growth and esg ratings 
mod <- lm(revenue_growth ~ esg, data = esg_grouped)


# linear regression (rev growth ~ esg) for each sector group
mm <- lmList(revenue_growth~esg|sector_group, esg_grouped)


groups <- unique(esg_grouped$sector_group)



# extract coefficients and p-values for each regression, put into array for table output

reg_stats <- array(NA, dim=c(6,4))

for (k in 1:length(groups)) {
  reg_stats[k, 1] <- groups[k]
  reg_stats[k, 2] <-  (summary(mm)$coeff)[groups[k], 'Estimate', 'esg']
  reg_stats[k, 3] <- (summary(mm)$coeff)[groups[k], 'Pr(>|t|)', 'esg']
}

reg_stats[6,1] <- 'All Groups'
reg_stats[6, 2] <- (summary(mod)$coeff)['esg', 'Estimate']
reg_stats[6, 3] <- (summary(mod)$coeff)['esg', 'Pr(>|t|)']

# convert coeffs. and p-values to data frame, rename variables

regression <- as.data.frame(reg_stats) %>%
  mutate('p-value' = as.numeric(V3), 'Coeff. Estimate' = as.numeric(V2)) %>%
  select('Sector Group' = V1, 'Coeff. Estimate', 'p-value')

# write out as csv (so this doesn't have to be done in index.rmd)
write.csv(regression, 'regression_data.csv')

# table output for regression results

kable(regression, digits = 4, row.names = FALSE,
      caption = 'Linear Regression: ESG Score Predicting Revenue Growth (Revenue Growth ~ ESG)') %>%
  kable_styling(bootstrap_options = c("striped", "hover"),
                full_width = F,
                font_size = 14,
                position = "left")



```

```{r}
#Loading Datasets
library(maps)
data(state)
library(viridis)
#Wrangling Datasets
USData <- esg %>%
  select(esg, State) %>%
  group_by(State) %>%
  summarize(ESG = mean(esg)) %>%
  mutate(State = tolower(State))
States <- map_data(map = "state"
                       , region = ".") 
#Merging with Map Dataset
USMap <- USData %>%
  right_join(States, by = c("State" = "region")) 

#Creating Map
ggplot(USMap, aes(x = long, y = lat, group = group
                      , fill = ESG)) +
  geom_polygon(color = "white") +
  theme_void() +
  coord_fixed(ratio = 1.3) +
  labs(title = "Which States House Sustainable Companies?"
       , subtitle = "The average ESG of companies headquartered in each state."
       , caption = "*Grey states do not contain a Top-75 Company"
       , fill = "Average ESG Score") +
  scale_fill_viridis(option = "brewer blues", direction = -1)

```

```{r}
#Global Sustainability Leaflet
library(maps)
library(leaflet)
#Data Wrangling
GlobalData <- WorldData %>%
  select(Company, Country) %>%
  mutate(`Country` = ifelse(`Country` == 'CA ','Canada',`Country`)) %>%
  mutate(`Country` = ifelse(`Country` == 'U.S. ','USA',`Country`)) %>%
  mutate(`Country` = as.character(`Country`)) %>%
  mutate(`Country` = gsub(" ","",`Country`))

#Adding Map Data
WorldMap <- map_data(map = "world", region = ".") %>%
  select(region, lat, long, group) %>%
  group_by(region) %>%
  summarize(long = mean(long),lat = mean(lat)) %>%
  rename(`Country` = region) %>%
  mutate(`Country` = gsub(" ","",`Country`))

#Merging Datasets
GlobalMap <- GlobalData %>%
  inner_join(WorldMap) %>%
  group_by(Country, long, lat) %>%
  summarize(Companies = paste(Company, collapse = "<br>"), count = n())

#Creating Global Sustainability Leaflet
GlobalLeaflet <- leaflet(GlobalMap) %>%
  addTiles() %>%
  addCircleMarkers(lat = ~lat
                   , lng = ~long
                   , popup = GlobalMap$Companies
                   , stroke = FALSE 
                   , radius = ~count
                   , fillOpacity = 0.9) 
GlobalLeaflet




  
```

